services:
  gateway:
    image: bwdesigngroup/ignition-docker:8.1.22
    hostname: gateway
    ports:
      - 8088
    volumes:
      - ./ignition-data:/workdir
      - ./backups/gateway.gwbk:/restore.gwbk
    environment:
      - SYMLINK_GITIGNORE=false
      - SYMLINK_LOGBACK=false

    # command: >
    #   -r /restore.gwbk